import Groq from 'groq-sdk';
import dotenv from 'dotenv';
import Draft from '../models/Draft.js';
import ActionHistory from '../models/ActionHistory.js';

dotenv.config();

// 1. Gather all Groq keys from .env
const apiKeys = [
  process.env.GROQ_API_KEY_1 || process.env.GROQ_API_KEY,
  process.env.GROQ_API_KEY_2,
  process.env.GROQ_API_KEY_3
].filter(Boolean);

let currentKeyIndex = 0;

// Fallback models in priority order
// Replace the MODELS array in server/controllers/aiController.js
const MODELS = [
  'qwen/qwen3.8-27b',
  'openai/gpt-oss-20b'
];

const callGroqWithFallback = async (messages, responseFormat = null) => {
  if (apiKeys.length === 0) {
    throw new Error('No Groq API keys configured in .env');
  }

  let attempts = 0;
  const maxAttempts = apiKeys.length * MODELS.length;

  while (attempts < maxAttempts) {
    const activeKey = apiKeys[currentKeyIndex];
    const groq = new Groq({ apiKey: activeKey });
    
    // Pick model based on current attempt phase
    const model = MODELS[attempts % MODELS.length];

    try {
      console.log(`🚀 Calling Groq API [Key #${currentKeyIndex + 1} | Model: ${model}]`);

      const params = {
        messages,
        model,
        temperature: 0.3,
      };

      if (responseFormat) {
        params.response_format = responseFormat;
      }

      const completion = await groq.chat.completions.create(params);
      return completion.choices[0]?.message?.content || '';

    } catch (error) {
      attempts++;
      const status = error.status || error.code;

      console.warn(`⚠️ Groq Request Failed (Status: ${status} | Key #${currentKeyIndex + 1} | Model: ${model})`);

      if (status === 413) {
        // Payload Too Large -> Truncate user content and retry immediately
        console.warn(`413 Payload Too Large. Truncating message body...`);
        const userMsg = messages.find(m => m.role === 'user');
        if (userMsg && typeof userMsg.content === 'string') {
          userMsg.content = userMsg.content.substring(0, 2000);
        }
      } else if (status === 429) {
        // Rate limit reached -> Rotate key immediately
        console.warn(`Rotating to Key #${((currentKeyIndex + 1) % apiKeys.length) + 1}...`);
        currentKeyIndex = (currentKeyIndex + 1) % apiKeys.length;
      } else if (status === 503 || status === 500) {
        // High demand / server hiccup -> Pause briefly and rotate key
        await new Promise((resolve) => setTimeout(resolve, 1000));
        currentKeyIndex = (currentKeyIndex + 1) % apiKeys.length;
      } else {
        throw error;
      }
    }
  }

  throw new Error('All Groq API keys and model fallbacks exhausted.');
};

export const generateReply = async (req, res) => {
  try {
    const { emailContext, tone = 'Concise and Professional', previousDraft, userPrompt } = req.body;

    if (!emailContext) {
      return res.status(400).json({ error: 'Email context is required' });
    }

    // Sanitize body length
    const cleanBody = (emailContext.body || emailContext.preview || '')
      .replace(/<[^>]*>?/gm, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      .substring(0, 3000);

    let userInstruction = `Draft a reply to this email:
From: ${emailContext.sender}
Subject: ${emailContext.subject}
Body: ${cleanBody}

Required Tone: ${tone}`;

    if (previousDraft && userPrompt) {
      userInstruction += `\n\nPrevious draft: "${previousDraft}"\nRefine it with this instruction: "${userPrompt}"`;
    }

    const messages = [
      {
        role: 'system',
        content: 'You are an intelligent email assistant. Output ONLY the raw email body text. Do not include subject lines, greetings, placeholders, or conversational filler like "Here is your draft:".'
      },
      {
        role: 'user',
        content: userInstruction
      }
    ];

    const draft = await callGroqWithFallback(messages);
    
    // Save to Mongo
    await Draft.create({
      userId: req.user.userId,
      recipient: emailContext.sender,
      subject: emailContext.subject,
      body: draft,
      status: 'AI Drafted',
      context: 'Generated by AI',
      time: 'Just now'
    });

    await ActionHistory.create({
      userId: req.user.userId,
      title: `Drafted reply to ${emailContext.sender}`,
      description: '1 message affected',
      status: 'Awaiting approval',
      time: 'Just now',
      previewSubject: emailContext.subject,
      previewBody: draft
    });

    res.json({ draft });

  } catch (error) {
    console.error('Error generating reply:', error);
    res.status(500).json({ error: error.message || 'Failed to generate reply' });
  }
};

export const processCommand = async (req, res) => {
  try {
    const { prompt } = req.body;
    if (!prompt) return res.status(400).json({ error: 'Prompt required' });

    const messages = [
      {
        role: 'system',
        content: 'You are an AI inbox organizer. Analyze the user command and return a JSON object with key "actions" containing a list of strings representing recommended actions.'
      },
      {
        role: 'user',
        content: prompt
      }
    ];

    // Enforce JSON output mode on Groq
    const rawResponse = await callGroqWithFallback(messages, { type: 'json_object' });

    let jsonResponse;
    try {
      jsonResponse = JSON.parse(rawResponse);
    } catch (e) {
      jsonResponse = { actions: [rawResponse] };
    }

    // Save to Mongo
    await ActionHistory.create({
      userId: req.user.userId,
      title: `Processed command: ${prompt.substring(0, 20)}...`,
      description: `${jsonResponse.actions ? jsonResponse.actions.length : 1} actions taken`,
      status: 'Completed',
      time: 'Just now',
      previewSubject: 'Command Execution',
      previewBody: JSON.stringify(jsonResponse.actions)
    });

    res.json({ result: jsonResponse });

  } catch (error) {
    console.error('Error processing command:', error);
    res.status(500).json({ error: error.message || 'Failed to process command' });
  }
};

export const getHistory = async (req, res) => {
  try {
    let actions = await ActionHistory.find({ userId: req.user.userId }).sort({ createdAt: -1 });
    
    const formattedActions = actions.map(a => ({
      id: a._id.toString(),
      title: a.title,
      description: a.description,
      status: a.status,
      time: a.time || new Date(a.createdAt).toLocaleDateString(),
      createdAt: a.createdAt,
      previewSubject: a.previewSubject,
      previewBody: a.previewBody,
      messagesAffected: a.messagesAffected
    }));
    
    const totalActions = formattedActions.length;
    const completedActions = formattedActions.filter(a => a.status === 'Completed').length;
    const totalMessagesAffected = formattedActions.reduce((acc, curr) => acc + (curr.messagesAffected || 1), 0);
    const estimatedHours = ((totalActions * 3) / 60).toFixed(1);
    const successPercentage = totalActions > 0 ? ((completedActions / totalActions) * 100).toFixed(1) : '100.0';

    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    const actionsThisWeek = formattedActions.filter(a => new Date(a.createdAt) >= sevenDaysAgo).length;

    res.json({
      metrics: {
        actionsThisWeek,
        messagesAffected: totalMessagesAffected,
        timeSaved: `${estimatedHours} hrs`,
        successRate: `${successPercentage}%`
      },
      actions: formattedActions
    });
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
};

export const generateSummary = async (req, res) => {
  try {
    const { emailContext, summaryType = 'detailed' } = req.body;

    if (!emailContext) {
      return res.status(400).json({ error: 'Email context is required' });
    }

    // Clean body HTML and slice long text to prevent 413 Payload Too Large
    const rawBody = emailContext.body || emailContext.preview || '';
    const cleanBody = rawBody
      .replace(/<[^>]*>?/gm, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      .substring(0, 3000);

    let lengthInstruction = '';
    if (summaryType === 'brief') {
      lengthInstruction = 'Provide a concise 1 to 2 sentence brief overview.';
    } else if (summaryType === 'detailed') {
      lengthInstruction = 'Provide a very long, highly detailed, and informative description of the email content. Break down the core intent, extract any important action items, highlight key entities/dates, and explain the full context comprehensively.';
    } else {
      lengthInstruction = 'Provide 3 short, actionable bullet points highlighting key details.';
    }

    const prompt = `From: ${emailContext.sender || 'Unknown'}
Subject: ${emailContext.subject || 'No Subject'}

Email Content:
${cleanBody}`;

    const messages = [
      { 
        role: 'system', 
        content: `You are an intelligent email summarization assistant. ${lengthInstruction} Do not include generic filler text or preamble.` 
      }, 
      { 
        role: 'user', 
        content: prompt 
      }
    ];

    const summary = await callGroqWithFallback(messages);
    res.json({ summary });

  } catch (error) { 
    console.error('Error generating summary:', error);
    res.status(500).json({ error: error.message || 'Failed to generate summary' }); 
  }
};
